config:
- port: 10032
- log: /tmp/xmppd.log
- pid: /tmp/xmppd.pid
- xmpp_server: mail.anzhi.com
- xmpp_port: 5222
- xmpp_username: jabber
- xmpp_password: jabber
- xmpp_domain: mail.anzhi.com
- xmpp_resource: may_be_this_host_name
